SRESX-219 generate grafana dashboard
bukalapak/mkdash pull request #1
Opened 2019-04-08 05:45 UTC by davidchrisx

2019-04-08 06:04 UTC, indrasaputra requested changes

2019-04-08 06:04 UTC, indrasaputra commented on Makefile
> +	dep ensure -v -vendor-only
pake go mod aja

2019-04-08 06:04 UTC, indrasaputra commented on Makefile
> +include .env
ini untuk apa?

2019-04-08 06:04 UTC, indrasaputra commented on Makefile
> +export $(shell sed 's/=.*//' .env)
ini untuk apa?

2019-04-08 06:04 UTC, indrasaputra commented on Makefile
> +export VERSION            ?= $(shell git show -q --format=%h)
ini untuk apa?

2019-04-08 06:04 UTC, indrasaputra commented on maker/maker.go
> +//Maker is a struct that connect to mkdash
hmm.. inkonsisten.
beri space setelah `//`

2019-04-08 06:04 UTC, indrasaputra commented on maker/maker.go
> +//New returns a maker struct for creating dashboard
ini jg

2019-04-08 06:04 UTC, indrasaputra commented on maker/maker.go
> +	client := &http.Client{}
ini apa bedanya sama `http.DefaultClient`?

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +//Parser is a struct that connect to mkdash
spasi setelah `//`

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +//Data is a struct that hold input data
ini jg

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +	Project string
kasi penjelasan dong Project ini apa

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +	Service string
kasi penjelasan dong Service ini apa

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +type Data struct {
kalo memang kebutuhannya untuk input data, lebih nama struct nya jg `InputData`

2019-04-08 06:04 UTC, indrasaputra commented on parser/parser.go
> +//New return a parser struct to pare data provided
spasi setelah `//`

2019-04-08 06:12 UTC, davidchrisx commented on Makefile
> +include .env
ini envnya saya masukin saat build mas jadi saya tambahin di makefile

2019-04-08 06:21 UTC, davidchrisx commented on maker/maker.go
> +	client := &http.Client{}
ga ada bedanya sih mas, setau saya DefaultClient = &client{}

2019-04-08 14:05 UTC, indrasaputra requested changes

2019-04-08 14:05 UTC, indrasaputra commented on maker/maker.go
> +	client := &http.Client{}
@davidchrisx lebih baik diberi timeout. jadi kalau ada masalah dgn Grafana, proses ini bisa segera ngasi tau bahwa ada error daripada idle lama.
ga terlalu ngefek karena bukan service production, tp ini jadi salah satu pembelajaran buat menerapkan best practice.

baca lebih lanjut: https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

2019-04-08 14:09 UTC, indrasaputra commented
@davidchrisx ke depannya, kalau develop project/service, usahakan 1 PR 1 goal ya.
ini saya lihat ada beberapa goal, yg seharusnya bisa dibagi2 menjadi beberapa PR tersendiri:
- main business 
- build project


kemudian, commit harus menjelaskan maksud perubahan yg dilakukan, bukan cuma ngasi nomor story dan tidak menjelaskan apapun. seharusnya ini sudah menjadi best practice sejak dulu, yang entah mengapa masih sering terulang kesalahan seperti ini.

2019-04-08 14:27 UTC, davidchrisx commented
> @davidchrisx ke depannya, kalau develop project/service, usahakan 1 PR 1 goal ya.
> ini saya lihat ada beberapa goal, yg seharusnya bisa dibagi2 menjadi beberapa PR tersendiri:
> 
> * main business
> * build project
> 
> kemudian, commit harus menjelaskan maksud perubahan yg dilakukan, bukan cuma ngasi nomor story dan tidak menjelaskan apapun. seharusnya ini sudah menjadi best practice sejak dulu, yang entah mengapa masih sering terulang kesalahan seperti ini.

oke mas noted, tadi nya ini maunya cuman main.go doang karena kecil tapi pas mau bikin tesnya ribet jadi dipisah2 🙈

2019-04-09 07:14 UTC, indrasaputra requested changes

2019-04-09 07:14 UTC, indrasaputra commented on maker/maker.go
> +	timeOutSecond int
di golang, untuk timeout seperti ini lebih baik pake time.Duration

2019-04-09 07:15 UTC, indrasaputra commented
@davidchrisx tinggal review minor yaa.

ini nanti aplikasi nya berupa cli?

2019-04-09 07:34 UTC, davidchrisx commented
> @davidchrisx tinggal review minor yaa.
> 
> ini nanti aplikasi nya berupa cli?

iya mas dalam bentuk cli

2019-04-09 07:48 UTC, indrasaputra commented
@davidchrisx LGTM. monggo dimerge.

next PR nya, cli nya bisa nerima auth ya biar ga perlu dimasukin ke env var.
e.g:

```
mkdash -auth="your-auth" <project> <service>
```

2019-04-09 07:50 UTC, indrasaputra approved these changes

2019-04-09 08:27 UTC, merged